// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehopbkorzoiinhrfjvvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVob3Bia29yem9paW5ocmZqdnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTYwNTAsImV4cCI6MjA2NjI3MjA1MH0.ZNobG_L1NiiDEZBwsm3vpbhGwjP_W-2tfLw2FTZdlQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});